management:
  endpoints:
    web:
      exposure:
        include:
          '*'
          
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: nuwan
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
